# Endereço do Servidor de Proxy (IP ou Domínio)
server_ip = "localhost"

# Token de Matrícula (Define a qual grupo este cliente pertencerá)
# O servidor usa isso para autorizar e gerar o certificado mTLS automaticamente
token = "$2a$14$vvCCM7/Pn"

enroll_secret = "seu-segredo-super-dificil"

#Nome de matricula
name = "CMT-PROXY"
# Configurações de Conexão
control_port = ":8081"   # Porta do Túnel mTLS
enroll_port  = ":8082"   # Porta para pegar o certificado
reconnect_delay = 5      # Segundos para tentar reconectar